# For testing on different servers (Advanced Way)
name: Matrix Configuration 2

on:
  push: 
  workflow_dispatch:

jobs:
  deploy:
    environment: develop
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - images: alpine
          - os: windows-latest
       
    runs-on: ${{ matrix.os }}

    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Docker Images on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}

  
    
  