name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: 'dev'

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy Application
      run: |
        echo "Deploying to ${{ inputs.environment }} environment"